### ISSUE TITLE
Quest Tracker Flickering (supervillain-ui-1.3.9 / supervillain-ui-master)

### ISSUE THREAD

**Issue by FelesNoctis** [FailcoderAddons/supervillain-ui#89]
I recently got back into WoW, and grabbed the newest version of SVUI from Curse. I noticed that while most things seemed to be alright, there were a few kinks. Discovering there were some changes here, I downloaded this version, and while it fixed some problems, one major one that seems to be consistent between both is the Quest Tracker flickering.

When left alone to just display current quests it'll blink every so often. When actively tracking a quest it turns into a rave party, flickering rapidly. The coordinates display under the minimap also seems to be affected periodically, but it seems only when actively tracking a quest.

I've tested this on two different computers with different hardware, graphical configurations, and SVUI settings adjustments, same problem. I thought it might be a mismatch with my frame-rate so I tried vsync, no change. I disabled all other addons besides SVUI, it didn't appear to help. I've cleaned my cache and WTF folders with no change. I went through turning bits of SVUI on and off by themselves, and the one that seems to be causing the extreme flickering is the Unitframes portion, oddly enough. With SVUI_Unitframes disabled the flickering is reduced to the slow, periodic blink regardless of tracking a quest or not.

Visual example:
https://i.gyazo.com/55b23aed8da74f5e6da30169d4e501ea.mp4

When reduced to just SVUI_!Core and SVUI_QuestTracker the slow blink remains.

**Comment by joeymagz** [comment]
Don't use the version from Curse. Please use the latest version from here and tell me if it still happens.

**Comment by FelesNoctis** [comment]
At the time of posting I **WAS** using the latest version from here, the problem continued. I switched to another UI a couple days back, it was too distracting.
-----
1.) Cleared Cache
2.) Wiped WTF
3.) Wiped Interface
4.) Installed newest commit of SVUI
5.) Disabled Track-O-Matic

https://i.gyazo.com/ea0c1b77f897090daf030cc19744bb31.mp4

The rapid strobing has been fixed, but SVUI's quest tracker still seems to be blinking periodically. This time I caught it changing the icon of the active quest, that might be related? Every time I click on the quest's track icon it switches to the question mark, there's a blink a moment or two later, and it's back to an exclamation.

**Comment by finalsliver** [comment]
Confirmed still present, only blinks the quests, not tracked achievements.

![QuestDock](http://i.imgur.com/8kYEk7W.gifv)

**Comment by OrbitStorm** [comment]
I've been experiencing this issue as well, so you're not alone. Seems to have been introduced sometime midway through Legion as this was never present during WoD.
